In [10]:
from smart.model import ModelJoueurConvolution
from smart.video import Video, Image
import tensorflow as tf
import numpy as np
import os
import cv2

In [11]:
test_path = 'img/JHaut/revers/1980-2563309/images'
# path_dataset = 'img/JBas'

In [17]:
model_joueur_conv = ModelJoueurConvolution.load_model_from_path("saved_models/model_1_joueur_bas_conv.h5")
model_joueur_conv.summary_model

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 48, 748, 16)       448       
                                                                 
 batch_normalization (BatchN  (None, 48, 748, 16)      64        
 ormalization)                                                   
                                                                 
 max_pooling2d (MaxPooling2D  (None, 24, 374, 16)      0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 24, 374, 16)       0         
                                                                 
 conv2d_1 (Conv2D)           (None, 22, 372, 32)       4640      
                                                                 
 batch_normalization_1 (Batc  (None, 22, 372, 32)     

In [18]:
# Step 1: Load the data
list_videos, y = model_joueur_conv.analyse_sequence_frame(path_data_frame=path_dataset)

In [19]:
# Step 2: Label encoder
y = model_joueur_conv.label_encoder(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3], dtype=int64)

In [20]:
# Step 3: Split the data
X_train, y_train, X_test, y_test = model_joueur_conv.split_train_test(list_videos, y)
X_test.shape

(14, 50, 750, 3)

In [21]:
model_joueur_conv.evaluate(X_test, y_test)

1/1 [==============================] - 0s 153ms/step - loss: 15.3824 - accuracy: 0.4286
Loss:  15.382411003112793
Accuracy:  0.4285714328289032


[15.382411003112793, 0.4285714328289032]

# Test sur une vidéo particulier

In [4]:
# Traitement des frames et video
frames = []
for file in os.listdir(test_path):
    path_file = os.path.join(test_path, file)
    img_obj = Image.load_image(cv2.IMREAD_GRAYSCALE, path_file)
    img = img_obj.img
    frames.append(img)
frames

[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0

In [5]:
vid = Video.read_video_from_frames(frames)
vid.frames.shape

(15, 50, 50)

In [6]:
seq_vid = vid.frames.reshape((1, 15*50*50))
seq_vid

array([[0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [9]:
all_output_label = ['coup droit', 'deplacement', 'service', 'revers']

In [10]:
lab = model_joueur_conv.predict_label(seq_vid, all_output_label)
lab

1/1 [==============================] - 0s 23ms/step


array(['revers'], dtype='<U11')