In [27]:
from smart.model import ModelJoueurClassique
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, BatchNormalization, Dropout
import numpy as np

In [2]:
path_dataset = 'img/JHaut'

In [3]:
layers = [               
    tf.keras.Input(shape = 50*50*15), # 50*50 * 15 = 37500
    Dense(units=16, activation="relu"),
    Dense(units=32, activation="relu"),
    Dense(units=64, activation="sigmoid"),
    Dense(units=128, activation="relu"),
    Dense(units=4, activation="softmax")
]

In [4]:
model_joueur_classique = ModelJoueurClassique.load_model_from_layers(layers)
model_joueur_classique.summary_model

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                600016    
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 64)                2112      
                                                                 
 dense_3 (Dense)             (None, 128)               8320      
                                                                 
 dense_4 (Dense)             (None, 4)                 516       
                                                                 
Total params: 611,508
Trainable params: 611,508
Non-trainable params: 0
_________________________________________________________________


In [6]:
# Step 1: Load the data
list_videos, y = model_joueur_classique.analyse_sequence_frame(path_data_frame=path_dataset)

In [7]:
# Step 2: Label encoder
y = model_joueur_classique.label_encoder(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3], dtype=int64)

In [8]:
# Step 3: Split the data
X_train, y_train, X_test, y_test = model_joueur_classique.split_train_test(list_videos, y)
X_train.shape

(53, 37500)

In [9]:
# Step 4: Normalize the data
X_train, X_test = model_joueur_classique.normalize_input(X_train, X_test)

In [10]:
# Step 5: Train the model
history = model_joueur_classique.train(X_train, y_train)

Epoch 1/70
1/2 [==============>...............] - ETA: 0s - loss: 1.6330 - accuracy: 0.0000e+00
Epoch 1: val_loss improved from inf to 1.29607, saving model to checkpoints\Weights-001--1.29607.hdf5
2/2 [==============================] - 1s 160ms/step - loss: 1.6056 - accuracy: 0.0000e+00 - val_loss: 1.2961 - val_accuracy: 0.6364
Epoch 2/70
1/2 [==============>...............] - ETA: 0s - loss: 1.4207 - accuracy: 0.2500
Epoch 2: val_loss did not improve from 1.29607
2/2 [==============================] - 0s 34ms/step - loss: 1.4040 - accuracy: 0.2619 - val_loss: 1.6097 - val_accuracy: 0.0000e+00
Epoch 3/70
1/2 [==============>...............] - ETA: 0s - loss: 1.2584 - accuracy: 0.7500
Epoch 3: val_loss did not improve from 1.29607
2/2 [==============================] - 0s 32ms/step - loss: 1.2484 - accuracy: 0.7619 - val_loss: 1.9413 - val_accuracy: 0.0000e+00
Epoch 4/70
1/2 [==============>...............] - ETA: 0s - loss: 1.1321 - accuracy: 0.6562
Epoch 4: val_loss did not improve f

In [11]:
# Step 6: evaluate
loss, accuracy = model_joueur_classique.evaluate(X_test, y_test)

1/1 [==============================] - 0s 17ms/step - loss: 2.1769 - accuracy: 0.5714
Loss:  2.1769444942474365
Accuracy:  0.5714285969734192


In [25]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
example_input = np.reshape(X_test[0], (1, 50*50*15))
example_input

array([[0., 0., 0., ..., 0., 0., 0.]])

In [29]:
# Step 7: predict
y_pred = model_joueur_classique.predict(example_input)
y_pred

1/1 [==============================] - 0s 16ms/step


array([0], dtype=int64)

In [32]:
# Final step: save the model
model_joueur_classique.save_model('saved_models/model_joueur_haut.h5')