In [1]:
import pandas as pd
import numpy as np
from smart.model import NNModelBalle
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import tensorflow as tf
from keras import layers
from keras import models
from keras import optimizers
from keras import losses
from keras import metrics
from keras import regularizers

In [2]:
df = pd.read_csv('dataset/datasetTrajectoire - Copy.csv')
df

col1_1  col1_2  col2_1  col2_2  col3_1  col3_2  col4_1  col4_2  col5_1  \
0        210     316     217     285     232     281     230     295     246   
1        211     292     239     305     222     290     228     273     247   
2        213     318     235     300     247     307     239     294     242   
3        213     316     215     304     225     286     229     293     248   
4        213     318     242     301     226     304     237     302     239   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
3563     558     295     551     307     531     304     544     272     524   
3564     558     307     552     305     554     306     544     286     539   
3565     558     310     542     289     530     290     532     282     520   
3566     559     317     529     312     536     290     527     283     535   
3567     559     316     558     307     538     280     545     288     544   

      col5_2  ...  col41_2  col42_1  col42_2  col43_1  col43_2  col44_1  \
0        264  ...      133      497      103      519      110      514   
1        276  ...      110      486      110      520      111      528   
2        279  ...      112      514      109      524       84      502   
3        283  ...      127      501      106      505      105      513   
4        280  ...      110      499      102      516       95      525   
...      ...  ...      ...      ...      ...      ...      ...      ...   
3563     256  ...       59      414       58      415       47      426   
3564     259  ...       74      410       40      414       46      421   
3565     279  ...       74      418       55      418       47      417   
3566     259  ...       60      423       47      412       33      412   
3567     276  ...       62      417       45      423       33      404   

      col44_2  col45_1  col45_2  label  
0          96      526       67      1  
1          80      510       80      1  
2          84      526       86      1  
3          93      534       86      1  
4          74      535       90      1  
...       ...      ...      ...    ...  
3563       30      416       39     12  
3564       43      416       31     12  
3565       43      405       29     12  
3566       54      408       38     12  
3567       28      422       28     12  

[3568 rows x 91 columns]

In [3]:
X = df.drop(['label'], axis=1).values
y = df['label'].values
y.shape

(3568,)

In [4]:
# Avant encoder y
np.unique(y)

array([ 1,  3,  4,  6,  7,  8, 10, 11, 12], dtype=int64)

In [5]:
layers = [
    tf.keras.Input(shape = 90),
    layers.Dense(units=64, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
    layers.Dense(units=96, activation='relu'),
    layers.Dense(units=9, activation='softmax')
]

In [6]:
# Load the data
model = NNModelBalle.load_model_from_layers(layers)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                5824      
                                                                 
 dense_1 (Dense)             (None, 96)                6240      
                                                                 
 dense_2 (Dense)             (None, 9)                 873       
                                                                 
Total params: 12,937
Trainable params: 12,937
Non-trainable params: 0
_________________________________________________________________


In [7]:
# Normalize the data
scaler = StandardScaler()
encoder = LabelEncoder()

In [8]:
X = scaler.fit_transform(X)
y = encoder.fit_transform(y)
y

array([0, 0, 0, ..., 8, 8, 8], dtype=int64)

In [9]:
output_y = np.unique(y)
output_y

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [10]:
# Split the data
X_train, X_test, y_train, y_test = model.split_train_test(X, y, test_size=0.2, random_state=42)

In [11]:
# Train the model
model.train(X_train, y_train, epochs=80, learning_rate=0.0001)

Epoch 1/80
23/23 [==============================] - 1s 3ms/step - loss: 2.9643 - accuracy: 0.2106
Epoch 2/80
23/23 [==============================] - 0s 4ms/step - loss: 2.7869 - accuracy: 0.2561
Epoch 3/80
23/23 [==============================] - 0s 4ms/step - loss: 2.6419 - accuracy: 0.2971
Epoch 4/80
23/23 [==============================] - 0s 3ms/step - loss: 2.5191 - accuracy: 0.3560
Epoch 5/80
23/23 [==============================] - 0s 4ms/step - loss: 2.4124 - accuracy: 0.4467
Epoch 6/80
23/23 [==============================] - 0s 3ms/step - loss: 2.3169 - accuracy: 0.5130
Epoch 7/80
23/23 [==============================] - 0s 3ms/step - loss: 2.2287 - accuracy: 0.5459
Epoch 8/80
23/23 [==============================] - 0s 3ms/step - loss: 2.1479 - accuracy: 0.5939
Epoch 9/80
23/23 [==============================] - 0s 3ms/step - loss: 2.0723 - accuracy: 0.6324
Epoch 10/80
23/23 [==============================] - 0s 4ms/step - loss: 2.0004 - accuracy: 0.6692
Epoch 11/80
23/23 [

In [ ]:
# Evaluate the model
model.evaluate(X_test, y_test)

# Test

In [12]:
test_df = pd.read_csv('dataset/datasetTest - Copy.csv')
test_df

col1_1  col1_2  col2_1  col2_2  col3_1  col3_2  col4_1  col4_2  col5_1  \
0     238.5    31.5   244.5    39.5   227.5    38.5   246.5    42.5   238.5   
1     237.5    36.5   232.5    31.5   239.5    34.5   236.5    28.5   227.5   
2     239.5    39.5   238.5    39.5   246.5    24.5   245.5    34.5   236.5   
3     238.5    33.5   237.5    30.5   240.5    41.5   232.5    40.5   222.5   
4     228.5    41.5   235.5    26.5   239.5    38.5   242.5    39.5   223.5   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
700   253.0   270.0   260.0   273.0   243.0   286.0   255.0   278.0   250.0   
701   246.0   270.0   243.0   274.0   257.0   284.0   247.0   289.0   252.0   
702   242.0   283.0   243.0   282.0   254.0   289.0   249.0   287.0   255.0   
703   248.0   285.0   256.0   280.0   246.0   278.0   261.0   275.0   242.0   
704   260.0   275.0   242.0   281.0   252.0   282.0   259.0   284.0   257.0   

     col5_2  ...  col41_2  col42_1  col42_2  col43_1  col43_2  col44_1  \
0      46.0  ...     69.0    384.5     78.0    372.5     69.0    379.5   
1      32.0  ...     62.0    375.5     77.0    376.5     69.0    375.5   
2      33.0  ...     75.0    366.5     67.0    383.5     72.0    366.5   
3      43.0  ...     74.0    381.5     78.0    373.5     60.0    366.5   
4      43.0  ...     77.0    367.5     66.0    382.5     63.0    369.5   
..      ...  ...      ...      ...      ...      ...      ...      ...   
700   289.0  ...     73.0    346.0     66.0    344.0     71.0    332.0   
701   289.0  ...     73.0    340.0     63.0    330.0     70.0    328.0   
702   277.0  ...     56.0    342.0     62.0    331.0     69.0    342.0   
703   284.0  ...     65.0    331.0     67.0    338.0     60.0    344.0   
704   281.0  ...     58.0    343.0     74.0    344.0     70.0    346.0   

     col44_2  col45_1  col45_2  label  
0       66.0    373.5     76.0      1  
1       75.0    373.5     73.0      1  
2       77.0    372.5     76.0      1  
3       61.0    369.5     73.0      1  
4       60.0    376.5     78.0      1  
..       ...      ...      ...    ...  
700     67.0    341.0     56.0     10  
701     69.0    337.0     73.0     10  
702     66.0    339.0     65.0     10  
703     67.0    335.0     68.0     10  
704     62.0    334.0     74.0     10  

[705 rows x 91 columns]

In [13]:
X_test_fin = test_df.drop(['label'], axis=1).values
y_test_fin = test_df['label'].values
y_test_fin.shape

(705,)

In [14]:
# Avant encoder y_test_fin
np.unique(y_test_fin)

array([ 1,  6, 10], dtype=int64)

In [15]:
new_scaler = StandardScaler()

In [16]:
X_test_fin = new_scaler.fit_transform(X_test_fin)
y_test_fin = encoder.transform(y_test_fin)
y_test_fin

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [17]:
# Apres encoder y_test_fin
output_y_test_fin = np.unique(y_test_fin)
output_y_test_fin

array([0, 3, 6], dtype=int64)

In [18]:
# Step 4: Evaluate the model
score = model.evaluate(X_test_fin, y_test_fin)
score

23/23 [==============================] - 0s 2ms/step - loss: 5.9263 - accuracy: 0.1901
Loss:  5.926254749298096
Accuracy:  0.19007092714309692


[5.926254749298096, 0.19007092714309692]

In [19]:
# model.save_model('saved_models/NeuralNetworkModel_balle.h5')

In [ ]:
# Step 5: Predict
y_pred = model.predict(X_test_fin)
y_pred, y_test_fin

In [ ]:
# Confusion matrix
confusion_matrix(y_test_fin, y_pred)

In [ ]:
print(classification_report(y_test_fin, y_pred))