In [1]:
from smart.model import ModelJoueurClassique
from smart.video import Video, Image
import tensorflow as tf
import numpy as np
import os
import cv2

In [2]:
test_path = 'img/JHaut/revers/1980-2563309/images'

In [3]:
model_joueur = ModelJoueurClassique.load_model_from_path("saved_models/classic_model_1_joueur_haut.h5")
model_joueur.summary_model

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                600016    
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 64)                2112      
                                                                 
 dense_3 (Dense)             (None, 128)               8320      
                                                                 
 dense_4 (Dense)             (None, 4)                 516       
                                                                 
Total params: 611,508
Trainable params: 611,508
Non-trainable params: 0
_________________________________________________________________


In [4]:
# Traitement des frames et video
frames = []
for file in os.listdir(test_path):
    path_file = os.path.join(test_path, file)
    img_obj = Image.load_image(cv2.IMREAD_GRAYSCALE, path_file)
    img = img_obj.img
    frames.append(img)
frames

[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0

In [5]:
vid = Video.read_video_from_frames(frames)
vid.frames.shape

(15, 50, 50)

In [6]:
seq_vid = vid.frames.reshape((1, 15*50*50))
seq_vid

array([[0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [9]:
all_output_label = ['coup droit', 'deplacement', 'service', 'revers']

In [10]:
lab = model_joueur.predict_label(seq_vid, all_output_label)
lab

1/1 [==============================] - 0s 23ms/step


array(['revers'], dtype='<U11')