In [1]:
from smart.model import ModelJoueurConvolution
import tensorflow as tf
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, BatchNormalization, Dropout
import numpy as np

In [2]:
path_dataset = 'img/JHaut'

In [3]:
layers =  [
    tf.keras.Input(shape = (50, 750, 3)), # 50, 15*50, 3
    Conv2D(filters=16, kernel_size=(3, 3), activation="relu"),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2, 2)),
    Dropout(0.2),
        
    Conv2D(filters=32, kernel_size=(3, 3), activation="relu"),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2, 2)),
    Dropout(0.2),
        
    Conv2D(filters=64, kernel_size=(3, 3), activation="relu"),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2, 2)),
    Dropout(0.2),
        
    Flatten(),
    Dense(units=128, activation="relu"),
    Dense(units=4, activation="softmax"),
]

In [4]:
model_joueur_conv = ModelJoueurConvolution.load_model_from_layers(layers)
model_joueur_conv.summary_model

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 48, 748, 16)       448       
                                                                 
 batch_normalization (BatchN  (None, 48, 748, 16)      64        
 ormalization)                                                   
                                                                 
 max_pooling2d (MaxPooling2D  (None, 24, 374, 16)      0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 24, 374, 16)       0         
                                                                 
 conv2d_1 (Conv2D)           (None, 22, 372, 32)       4640      
                                                                 
 batch_normalization_1 (Batc  (None, 22, 372, 32)      1

In [5]:
# Step 1: Load the data
list_videos, y = model_joueur_conv.analyse_sequence_frame(path_data_frame=path_dataset)

In [6]:
# Step 2: Label encoder
y = model_joueur_conv.label_encoder(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3], dtype=int64)

In [8]:
# Step 3: Split the data
X_train, y_train, X_test, y_test = model_joueur_conv.split_train_test(list_videos, y)
X_test.shape

(14, 50, 750, 3)

In [9]:
# Step 4: Normalize the data
X_train, X_test = model_joueur_conv.normalize_input(X_train, X_test)

In [10]:
# Step 5: Train the model
history = model_joueur_conv.train(X_train, y_train)

Epoch 1/70
2/2 [==============================] - ETA: 0s - loss: 27.9398 - accuracy: 0.2619
Epoch 1: val_loss improved from inf to 10.58330, saving model to checkpoints\Weights-001--10.58330.hdf5
2/2 [==============================] - 3s 819ms/step - loss: 27.9398 - accuracy: 0.2619 - val_loss: 10.5833 - val_accuracy: 0.0000e+00
Epoch 2/70
2/2 [==============================] - ETA: 0s - loss: 97.7383 - accuracy: 0.3095 
Epoch 2: val_loss improved from 10.58330 to 4.38824, saving model to checkpoints\Weights-002--4.38824.hdf5
2/2 [==============================] - 1s 360ms/step - loss: 97.7383 - accuracy: 0.3095 - val_loss: 4.3882 - val_accuracy: 0.0000e+00
Epoch 3/70
2/2 [==============================] - ETA: 0s - loss: 20.3291 - accuracy: 0.4286
Epoch 3: val_loss improved from 4.38824 to 3.21795, saving model to checkpoints\Weights-003--3.21795.hdf5
2/2 [==============================] - 1s 335ms/step - loss: 20.3291 - accuracy: 0.4286 - val_loss: 3.2180 - val_accuracy: 0.0000e+00


In [11]:
# Step 6: evaluate
loss, accuracy = model_joueur_conv.evaluate(X_test, y_test)

1/1 [==============================] - 0s 106ms/step - loss: 4.4070 - accuracy: 0.2143
Loss:  4.4070000648498535
Accuracy:  0.2142857164144516


In [15]:
X_test.shape

(14, 50, 750, 3)

In [16]:
example_input = np.reshape(X_test[0], (1, 50, 750, 3))
example_input

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [17]:
# Step 7: predict
y_pred = model_joueur_conv.predict(example_input)
y_pred

1/1 [==============================] - 0s 211ms/step


array([2], dtype=int64)

In [18]:
# Final step: save the model
model_joueur_conv.save_model('saved_models/model_1_joueur_haut_conv.h5')