In [1]:
from smart.model import ModelJoueurClassique
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, BatchNormalization, Dropout
import numpy as np

In [16]:
path_dataset = 'img/JHaut'

In [17]:
model_joueur_classique = ModelJoueurClassique.load_model_from_path("saved_models/classic_model_1_joueur_haut.h5")
model_joueur_classique.summary_model

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                600016    
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 64)                2112      
                                                                 
 dense_3 (Dense)             (None, 128)               8320      
                                                                 
 dense_4 (Dense)             (None, 4)                 516       
                                                                 
Total params: 611,508
Trainable params: 611,508
Non-trainable params: 0
_________________________________________________________________


In [18]:
# Step 1: Load the data
list_videos, y = model_joueur_classique.analyse_sequence_frame(path_data_frame=path_dataset)

In [19]:
# Step 2: Label encoder
y = model_joueur_classique.label_encoder(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3], dtype=int64)

In [20]:
# Step 3: Split the data
X_train, y_train, X_test, y_test = model_joueur_classique.split_train_test(list_videos, y)
X_test.shape

(14, 37500)

In [21]:
# Step 4: Normalize the data
X_train, X_test = model_joueur_classique.normalize_input(X_train, X_test)

In [22]:
# Step 5: Train the model
history = model_joueur_classique.train(X_train, y_train, epochs=100)

Epoch 1/100
1/2 [==============>...............] - ETA: 0s - loss: 0.0012 - accuracy: 1.0000
Epoch 1: val_loss improved from inf to 7.89873, saving model to checkpoints\Weights-001--7.89873.hdf5
2/2 [==============================] - 1s 249ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 7.8987 - val_accuracy: 0.0000e+00
Epoch 2/100
1/2 [==============>...............] - ETA: 0s - loss: 6.7494e-04 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 7.89873
2/2 [==============================] - 0s 54ms/step - loss: 6.2990e-04 - accuracy: 1.0000 - val_loss: 8.2885 - val_accuracy: 0.0000e+00
Epoch 3/100
1/2 [==============>...............] - ETA: 0s - loss: 3.6736e-04 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 7.89873
2/2 [==============================] - 0s 53ms/step - loss: 3.5551e-04 - accuracy: 1.0000 - val_loss: 8.7767 - val_accuracy: 0.0000e+00
Epoch 4/100
1/2 [==============>...............] - ETA: 0s - loss: 2.2609e-04 - accuracy: 1.0000
Epoch 4: val_lo

In [23]:
# Step 6: evaluate
loss, accuracy = model_joueur_classique.evaluate(X_test, y_test)

1/1 [==============================] - 0s 25ms/step - loss: 3.4565 - accuracy: 0.5714
Loss:  3.456465005874634
Accuracy:  0.5714285969734192


In [24]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
example_input = np.reshape(X_test[0], (1, 50*50*15))
example_input

array([[0., 0., 0., ..., 0., 0., 0.]])

In [26]:
# Step 7: predict
y_pred = model_joueur_classique.predict(example_input)
y_pred

1/1 [==============================] - 0s 65ms/step


array([0], dtype=int64)

In [29]:
possible_outputs = ['coup droit', 'revers', 'service', 'deplacement']

In [30]:
pred_label = model_joueur_classique.predict_label(example_input, possible_outputs)
pred_label

1/1 [==============================] - 0s 21ms/step


array(['coup droit'], dtype='<U11')

In [28]:
# Final step: save the model
model_joueur_classique.save_model('saved_models/classic_model_1_joueur_haut.h5')