In [296]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
from keras import layers
from keras import models
from keras import optimizers
from keras import losses
from keras import metrics
from keras import regularizers
from keras.utils import to_categorical
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [297]:
df = pd.read_csv('dataset/new_pos.csv')
df.head()

col1_0  col1_1  col2_0  col2_1  col3_0  col3_1  col4_0  col4_1  col5_0  \
0   175.0   232.0   184.0   227.0   195.0   229.0   200.0   215.0   196.0   
1   176.0   232.0   191.0   229.0   188.0   233.0   200.0   216.0   205.0   
2   176.0   236.0   191.0   226.0   196.0   227.0   200.0   221.0   199.0   
3   176.0   238.0   184.0   236.0   191.0   224.0   189.0   214.0   194.0   
4   176.0   242.0   185.0   231.0   191.0   228.0   187.0   224.0   195.0   

   col5_1  ...  col41_1  col42_0  col42_1  col43_0  col43_1  col44_0  col44_1  \
0   213.0  ...    119.0    374.0    114.0    371.0    110.0    380.0    108.0   
1   217.0  ...    121.0    377.0    110.0    374.0    107.0    383.0     97.0   
2   221.0  ...    113.0    375.0    106.0    377.0    110.0    378.0     97.0   
3   215.0  ...    120.0    368.0    105.0    380.0    108.0    384.0     96.0   
4   219.0  ...    113.0    374.0    105.0    373.0    109.0    380.0     98.0   

   col45_0  col45_1  col46  
0    391.0     93.0    2.0  
1    382.0    101.0    2.0  
2    383.0     95.0    2.0  
3    386.0     94.0    2.0  
4    392.0    102.0    2.0  

[5 rows x 91 columns]

In [298]:
df.describe()

col1_0       col1_1       col2_0       col2_1       col3_0  \
count  6463.000000  6463.000000  6463.000000  6463.000000  6463.000000   
mean    301.635928   172.079375   301.376141   169.084326   301.932230   
std      75.307941    70.621681    74.091861    67.475299    72.442872   
min     164.000000    88.000000   170.000000    87.000000   176.000000   
25%     246.000000   102.000000   245.000000   102.000000   247.000000   
50%     305.000000   222.000000   305.000000   215.000000   305.000000   
75%     361.000000   243.000000   360.000000   237.000000   358.000000   
max     435.000000   257.000000   432.000000   251.000000   428.000000   

            col3_1       col4_0       col4_1       col5_0       col5_1  ...  \
count  6463.000000  6463.000000  6463.000000  6463.000000  6463.000000  ...   
mean    166.213523   301.843571   163.366084   301.711898   160.375058  ...   
std      64.807385    71.027193    62.238422    69.215780    59.296313  ...   
min      79.000000   177.000000    79.000000   177.000000    72.000000  ...   
25%     102.000000   248.000000   104.000000   249.000000   106.000000  ...   
50%     211.000000   304.000000   205.000000   305.000000   195.000000  ...   
75%     231.000000   357.000000   225.000000   355.000000   220.000000  ...   
max     245.000000   425.000000   242.000000   425.000000   236.000000  ...   

           col41_1      col42_0      col42_1      col43_0      col43_1  \
count  6463.000000  6463.000000  6463.000000  6463.000000  6463.000000   
mean    155.641343   299.240755   155.738357   299.663160   156.079684   
std      54.250629    67.574223    57.554642    69.739207    60.446863   
min      76.000000   155.000000    73.000000   152.000000    70.000000   
25%     102.000000   249.000000    99.000000   247.000000    95.000000   
50%     143.000000   301.000000   140.000000   302.000000   138.000000   
75%     209.000000   351.000000   213.000000   353.000000   217.000000   
max     251.000000   452.000000   254.000000   455.000000   258.000000   

           col44_0      col44_1      col45_0      col45_1        col46  
count  6463.000000  6463.000000  6463.000000  6463.000000  6463.000000  
mean    299.417763   156.613337   299.710351   157.583475     6.844499  
std      71.757387    63.541532    73.292565    66.932465     3.456067  
min     146.000000    67.000000   143.000000    64.000000     2.000000  
25%     246.000000    92.000000   244.000000    89.000000     4.000000  
50%     303.000000   137.000000   303.000000   135.000000     7.000000  
75%     355.000000   222.000000   356.500000   228.000000    10.000000  
max     458.000000   261.000000   462.000000   265.000000    12.000000  

[8 rows x 91 columns]

In [299]:
X = df.drop('col46', axis=1).values
y = df['col46'].values

In [300]:
output_y = np.unique(y)
output_y

array([ 2.,  3.,  4.,  6.,  7.,  8., 10., 11., 12.])

In [301]:
X.shape

(6463, 90)

In [302]:
scaler = StandardScaler()

In [303]:
# Normalize the data
X = scaler.fit_transform(X)
X

array([[-1.68170479,  0.84853915, -1.58432007, ..., -0.76512318,
         1.24564767, -0.96497973],
       [-1.66842495,  0.84853915, -1.48983544, ..., -0.93825169,
         1.12284263, -0.84544702],
       [-1.66842495,  0.90518336, -1.48983544, ..., -0.93825169,
         1.13648763, -0.93509655],
       ...,
       [ 1.62497524,  1.01847178,  1.58766371, ..., -1.19007499,
         0.03124227, -1.27875309],
       [ 1.62497524,  1.07511599,  1.5471703 , ..., -1.26876977,
        -0.02333775, -1.29369468],
       [ 1.62497524,  1.07511599,  1.5336725 , ..., -1.19007499,
         0.00395226, -1.23392832]])

In [304]:
encoder = LabelEncoder()

In [305]:
y = encoder.fit_transform(y)
y

array([0, 0, 0, ..., 8, 8, 8], dtype=int64)

In [306]:
X_train, X_validation, y_train, y_validation = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape

(5170, 90)

In [307]:
# Classification model
tf.random.set_seed(1234) # for consistent results
model = models.Sequential(
    [
        tf.keras.Input(shape = 90),
        layers.Dense(units=64, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
        layers.Dense(units=96, activation='relu'),
        layers.Dense(units=len(output_y), activation='softmax')
    ]
)

In [308]:
model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_39 (Dense)            (None, 64)                5824      
                                                                 
 dense_40 (Dense)            (None, 96)                6240      
                                                                 
 dense_41 (Dense)            (None, 9)                 873       
                                                                 
Total params: 12,937
Trainable params: 12,937
Non-trainable params: 0
_________________________________________________________________


In [309]:
y_train

array([0, 1, 6, ..., 6, 7, 1], dtype=int64)

In [310]:
model.compile(
    optimizer=optimizers.Adam(learning_rate=0.001),
    loss=losses.SparseCategoricalCrossentropy(),
    metrics=[metrics.SparseCategoricalAccuracy()]
)

history = model.fit(X_train, y_train, epochs=100, batch_size=128, validation_split=0.2)

Epoch 1/100
33/33 [==============================] - 1s 10ms/step - loss: 2.3943 - sparse_categorical_accuracy: 0.5109 - val_loss: 1.8205 - val_sparse_categorical_accuracy: 0.7447
Epoch 2/100
33/33 [==============================] - 0s 11ms/step - loss: 1.4518 - sparse_categorical_accuracy: 0.8733 - val_loss: 1.1107 - val_sparse_categorical_accuracy: 0.9787
Epoch 3/100
33/33 [==============================] - 0s 6ms/step - loss: 0.9340 - sparse_categorical_accuracy: 0.9855 - val_loss: 0.7784 - val_sparse_categorical_accuracy: 0.9971
Epoch 4/100
33/33 [==============================] - 0s 6ms/step - loss: 0.6938 - sparse_categorical_accuracy: 0.9937 - val_loss: 0.6099 - val_sparse_categorical_accuracy: 0.9981
Epoch 5/100
33/33 [==============================] - 0s 4ms/step - loss: 0.5554 - sparse_categorical_accuracy: 0.9973 - val_loss: 0.4970 - val_sparse_categorical_accuracy: 1.0000
Epoch 6/100
33/33 [==============================] - 0s 5ms/step - loss: 0.4550 - sparse_categorical_ac

In [286]:
model.evaluate(X_validation, y_validation)

41/41 [==============================] - 0s 1ms/step - loss: 0.0072 - sparse_categorical_accuracy: 1.0000


[0.007187024690210819, 1.0]

In [200]:
model.save('saved_models/model_balle_2.h5')

# Test DataFrame

In [311]:
df_test = pd.read_csv('dataset/new_pos_test.csv')

In [312]:
X_test = df_test.drop('col46', axis=1).values
y_test = df_test['col46'].values
y_test

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  6.,  6.,  6.,  6.,  6.,  6.,
        7., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 12., 12.])

In [313]:
new_scaler = StandardScaler()

In [314]:
# Normalize the data
X_test = new_scaler.fit_transform(X_test)
X_test

array([[-0.44126302,  1.73114769, -0.62021034, ...,  0.53877629,
        -1.07149312,  0.51503057],
       [-0.69122102, -0.82738597, -0.89924692, ..., -1.19970385,
        -0.73968576, -1.1868736 ],
       [-2.36835862, -0.74701318, -2.78049355, ...,  0.92510521,
         0.22018553,  0.8932315 ],
       ...,
       [-0.58639992, -1.32971587,  0.5319407 , ...,  0.05253472,
         0.196485  , -0.11747787],
       [ 0.71176908, -1.45697278,  0.6669584 , ..., -0.83335746,
         0.15500908, -0.82171409],
       [-0.79604212, -1.63781155, -1.02526344, ...,  0.85183593,
         0.01280593,  0.82150374]])

In [315]:
y_test = encoder.transform(y_test)
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 4, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 8], dtype=int64)

In [316]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 4ms/step - loss: 7.8839 - sparse_categorical_accuracy: 0.3387


[7.8839111328125, 0.33870968222618103]

In [317]:
prediction = model.predict(X_test)
prediction

2/2 [==============================] - 0s 3ms/step


array([[9.29962844e-04, 9.21872258e-01, 3.44104483e-05, 1.24796643e-04,
        7.34079629e-02, 1.06857181e-06, 1.46981256e-05, 3.61481286e-03,
        2.78951315e-08],
       [9.16874111e-01, 9.55848955e-04, 1.09846434e-04, 1.90193805e-05,
        6.89268654e-06, 3.71734679e-08, 8.20276961e-02, 6.42599571e-06,
        7.67141657e-08],
       [2.65381247e-01, 1.49067730e-01, 5.74992537e-01, 7.12324181e-05,
        7.57114831e-05, 3.45727653e-06, 4.39867796e-03, 5.85540256e-05,
        5.95085742e-03],
       [1.11385293e-11, 5.17416862e-04, 1.98681297e-11, 2.67019956e-12,
        1.52777266e-05, 5.52456483e-11, 4.39026098e-06, 9.99462903e-01,
        3.39963124e-09],
       [9.99999642e-01, 5.34421822e-08, 2.03390769e-07, 9.75922347e-08,
        8.16526360e-12, 2.16088714e-15, 6.45401566e-10, 8.35699001e-18,
        1.03912247e-13],
       [8.75916034e-02, 1.42770051e-09, 4.03052419e-02, 3.37991696e-05,
        6.39583109e-11, 6.98234317e-07, 8.71711671e-01, 2.39413711e-10,
        3.5

In [318]:
y_pred = np.argmax(prediction, axis=1)
y_pred, y_test

(array([1, 0, 2, 7, 0, 6, 0, 0, 0, 2, 0, 7, 0, 0, 7, 1, 0, 7, 3, 7, 1, 0,
        7, 4, 7, 1, 0, 3, 7, 0, 7, 0, 0, 1, 1, 1, 7, 4, 3, 8, 6, 5, 6, 7,
        6, 0, 1, 5, 8, 7, 8, 7, 6, 1, 7, 7, 0, 7, 1, 7, 8, 8], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 4, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 8], dtype=int64))

In [319]:
confusion_matrix(y_test, y_pred)

array([[14,  4,  2,  2,  1,  0,  1,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  1,  1,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  3,  0,  0,  0,  2,  4,  7,  2],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2]], dtype=int64)

In [321]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.42      0.57        33
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.33      0.17      0.22         6
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         0
           6       0.80      0.20      0.32        20
           7       0.00      0.00      0.00         0
           8       0.40      1.00      0.57         2

    accuracy                           0.34        62
   macro avg       0.27      0.20      0.19        62
weighted avg       0.77      0.34      0.45        62



c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
