In [32]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from smart.model import RFModelBalle
from sklearn.preprocessing import StandardScaler, LabelEncoder
import joblib
from sklearn.metrics import confusion_matrix, classification_report

In [21]:
df = pd.read_csv('../dataset/new_pos_test.csv')
df

col1_0  col1_1  col2_0  col2_1  col3_0  col3_1  col4_0  col4_1  col5_0  \
0    264.0   269.5   264.0   269.5   264.0   269.5   264.0   269.5   264.0   
1    248.5    78.5   248.5    78.5   248.5    78.5   349.5   187.5   315.5   
2    144.5    84.5   144.0    84.5   144.5    84.5   145.5    83.5   217.5   
3    375.5   203.0   377.5   206.5   379.5   210.0   380.5   214.0   380.0   
4    268.0   175.0   268.0   175.0   268.0   175.0   268.0   175.0   268.0   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
57   368.0    80.5   368.0    80.5   368.0    80.5   368.0    80.5   248.0   
58   272.5    81.5   272.5    81.5   272.5    81.5   272.5    81.5   272.5   
59   255.0    41.0   328.0   239.0   321.0   221.0   314.0   203.0   308.0   
60   335.5    31.5   335.5    31.5   335.5    31.5   335.5    31.5   335.5   
61   242.0    18.0   241.5    17.5   241.5    19.5   248.5    72.5   247.5   

    col5_1  ...  col41_1  col42_0  col42_1  col43_0  col43_1  col44_0  \
0    269.5  ...    196.5    187.5    202.0    188.0    202.0    184.0   
1    150.5  ...     82.5    212.0     77.5    212.0     77.5    212.0   
2     76.5  ...    237.0    293.0    237.0    293.0    237.0    293.0   
3    214.0  ...    292.5    371.5    291.0    371.5    291.0    371.5   
4    175.0  ...     79.5    370.0     85.5    365.0     92.5    394.5   
..     ...  ...      ...      ...      ...      ...      ...      ...   
57   218.5  ...    192.0    323.5    193.5    322.5    195.0    321.0   
58    81.5  ...    199.0    335.5    199.0    335.5    199.0    335.5   
59   185.0  ...    200.5    266.0    199.0    278.0    185.0    285.0   
60    31.5  ...    105.0    287.0    105.0    287.0    105.0    287.0   
61    67.5  ...    232.5    270.0    228.5    275.0    231.5    275.5   

    col44_1  col45_0  col45_1  col46  
0     208.0    184.0    208.0    2.0  
1      77.5    212.0     77.5    2.0  
2     237.0    293.0    237.0    2.0  
3     291.0    371.5    291.0    2.0  
4      52.0    394.5     52.0    2.0  
..      ...      ...      ...    ...  
57    197.5    319.0    200.0   10.0  
58    199.0    335.5    199.0   10.0  
59    171.5    291.0    159.5   10.0  
60    105.0    287.5    105.5   12.0  
61    231.5    275.5    231.5   12.0  

[62 rows x 91 columns]

In [22]:
# Step 1: load the model
model_balle = RFModelBalle.load_model_from_path('../saved_models/model_balle_1.joblib')
model_balle

In [23]:
# Step 2: Read the data
X = df.drop(['col46'], axis=1)
y = df['col46']
y

0      2.0
1      2.0
2      2.0
3      2.0
4      2.0
      ... 
57    10.0
58    10.0
59    10.0
60    12.0
61    12.0
Name: col46, Length: 62, dtype: float64

In [24]:
# Step 3: Normalize X and encode y 
possible_outputs = [ 2,  3,  4,  6,  7,  8, 10, 11, 12]

In [25]:
scaler = StandardScaler()
encoder = LabelEncoder()

In [26]:
X = scaler.fit_transform(X)
encoder.fit(possible_outputs)
y = encoder.transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 4, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 8], dtype=int64)

In [29]:
# Step 4: Evaluate the model
score = model_balle.evaluate(X, y)
score

0.3709677419354839

In [31]:
# Step 5: Predict
y_pred = model_balle.predict(X)
y_pred, y

(array([1, 3, 6, 0, 0, 6, 0, 0, 0, 2, 0, 6, 0, 0, 2, 1, 0, 6, 3, 7, 1, 2,
        0, 0, 7, 2, 6, 0, 8, 0, 2, 0, 6, 1, 2, 4, 6, 2, 0, 4, 6, 4, 0, 7,
        6, 0, 0, 5, 6, 6, 6, 7, 6, 1, 2, 7, 0, 1, 1, 7, 8, 8], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 4, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 8], dtype=int64))

In [33]:
# Confusion matrix
confusion_matrix(y, y_pred)

array([[14,  3,  5,  2,  0,  0,  6,  2,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  2,  0,  1,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  3,  1,  0,  1,  1,  6,  4,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2]], dtype=int64)

In [34]:
print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       0.74      0.42      0.54        33
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         6
           4       0.33      1.00      0.50         1
           5       0.00      0.00      0.00         0
           6       0.46      0.30      0.36        20
           7       0.00      0.00      0.00         0
           8       0.67      1.00      0.80         2

    accuracy                           0.37        62
   macro avg       0.24      0.30      0.24        62
weighted avg       0.57      0.37      0.44        62



c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
