In [1]:
from smart.model import NNModelBalle
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

# Read data

In [3]:
df = pd.read_csv("../trajectoire/datasetsimple.csv")
df.head()

0      1      2      3      4      5      6      7      8      9  ...  \
0  231.0  304.0  250.0  287.0  266.0  287.0  252.0  283.0  275.0  284.0  ...   
1  230.0  304.0  239.0  303.0  242.0  297.0  263.0  263.0  281.0  273.0  ...   
2  227.0  306.0  248.0  282.0  247.0  296.0  271.0  278.0  255.0  268.0  ...   
3  236.0  304.0  250.0  280.0  239.0  273.0  251.0  287.0  261.0  261.0  ...   
4  248.0  286.0  251.0  294.0  265.0  296.0  260.0  266.0  269.0  283.0  ...   

     81     82    83     84    85     86    87     88    89  90  
0  73.0  495.0  56.0  490.0  68.0  516.0  78.0  503.0  62.0   1  
1  74.0  490.0  80.0  502.0  73.0  503.0  64.0  499.0  57.0   1  
2  80.0  502.0  61.0  513.0  66.0  493.0  57.0  522.0  51.0   1  
3  78.0  483.0  78.0  501.0  76.0  509.0  63.0  500.0  63.0   1  
4  82.0  484.0  77.0  496.0  73.0  491.0  65.0  512.0  56.0   1  

[5 rows x 91 columns]

In [3]:
# Step 1: Load model
model_balle = NNModelBalle.construct_model()
model_balle

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_24 (Dense)            (None, 64)                5824      
                                                                 
 dense_25 (Dense)            (None, 96)                6240      
                                                                 
 dense_26 (Dense)            (None, 9)                 873       
                                                                 
Total params: 12,937
Trainable params: 12,937
Non-trainable params: 0
_________________________________________________________________


In [4]:
# Step 2: Read the data
X = df.drop('col46', axis=1)
y = df['col46']

In [5]:
# Step 3: Normalize X and encode y 
possible_outputs = [ 2,  3,  4,  6,  7,  8, 10, 11, 12]

In [6]:
scaler = StandardScaler()
encoder = LabelEncoder()

In [7]:
X = scaler.fit_transform(X)
encoder.fit(possible_outputs)
y = encoder.transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 4, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 8], dtype=int64)

In [8]:
# Step 4: Evaluate the model
loss, accuracy = model_balle.evaluate(X, y)

2/2 [==============================] - 0s 4ms/step - loss: 7.3971 - sparse_categorical_accuracy: 0.3548
Loss:  7.397058486938477
Accuracy:  0.35483869910240173


In [9]:
# Step 5: Predict
y_pred = model_balle.predict(X)
y_pred

2/2 [==============================] - 0s 999us/step


array([1, 0, 2, 7, 0, 6, 0, 0, 0, 2, 0, 7, 0, 0, 7, 1, 0, 7, 3, 7, 1, 0,
       7, 4, 7, 2, 0, 0, 7, 0, 7, 0, 0, 1, 0, 1, 7, 5, 3, 8, 6, 5, 6, 7,
       6, 0, 1, 5, 8, 7, 8, 7, 6, 1, 5, 7, 0, 7, 1, 7, 8, 8], dtype=int64)

In [10]:
# Confusion matrix
confusion_matrix(y, y_pred)

array([[15,  3,  3,  1,  1,  0,  1,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  2,  0,  1,  0,  1,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  3,  0,  0,  0,  3,  4,  6,  2],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2]], dtype=int64)

In [11]:
print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.45      0.59        33
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.50      0.17      0.25         6
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         0
           6       0.80      0.20      0.32        20
           7       0.00      0.00      0.00         0
           8       0.40      1.00      0.57         2

    accuracy                           0.35        62
   macro avg       0.28      0.20      0.19        62
weighted avg       0.76      0.35      0.46        62



c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
