In [1]:
from smart.model import ModelJoueurClassique
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, BatchNormalization, Dropout
import numpy as np

In [2]:
path_dataset = 'img/JBas'

In [3]:
layers = [               
    tf.keras.Input(shape = 50*50*15), # 50*50 * 15 = 37500
    Dense(units=16, activation="relu"),
    Dense(units=32, activation="relu"),
    Dense(units=64, activation="sigmoid"),
    Dense(units=128, activation="relu"),
    Dense(units=4, activation="softmax")
]

In [4]:
model_joueur_classique = ModelJoueurClassique.load_model_from_layers(layers)
model_joueur_classique.summary_model

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                600016    
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 64)                2112      
                                                                 
 dense_3 (Dense)             (None, 128)               8320      
                                                                 
 dense_4 (Dense)             (None, 4)                 516       
                                                                 
Total params: 611,508
Trainable params: 611,508
Non-trainable params: 0
_________________________________________________________________


In [5]:
# Step 1: Load the data
list_videos, y = model_joueur_classique.analyse_sequence_frame(path_data_frame=path_dataset)

In [6]:
# Step 2: Label encoder
y = model_joueur_classique.label_encoder(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

In [7]:
# Step 3: Split the data
X_train, y_train, X_test, y_test = model_joueur_classique.split_train_test(list_videos, y)
X_train.shape

(171, 37500)

In [8]:
# Step 4: Normalize the data
X_train, X_test = model_joueur_classique.normalize_input(X_train, X_test)

In [11]:
# Step 5: Train the model
history = model_joueur_classique.train(X_train, y_train)

Epoch 1/70
1/5 [=====>........................] - ETA: 2s - loss: 4.9286e-04 - accuracy: 1.0000
Epoch 1: val_loss improved from inf to 7.63678, saving model to checkpoints\Weights-001--7.63678.hdf5
5/5 [==============================] - 1s 45ms/step - loss: 4.1301e-04 - accuracy: 1.0000 - val_loss: 7.6368 - val_accuracy: 0.0857
Epoch 2/70
1/5 [=====>........................] - ETA: 0s - loss: 2.2721e-04 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 7.63678
5/5 [==============================] - 0s 14ms/step - loss: 1.6267e-04 - accuracy: 1.0000 - val_loss: 8.7237 - val_accuracy: 0.0000e+00
Epoch 3/70
1/5 [=====>........................] - ETA: 0s - loss: 9.3913e-05 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 7.63678
5/5 [==============================] - 0s 16ms/step - loss: 6.9015e-05 - accuracy: 1.0000 - val_loss: 9.1821 - val_accuracy: 0.0000e+00
Epoch 4/70
1/5 [=====>........................] - ETA: 0s - loss: 4.3432e-05 - accuracy: 1.0000
Epoch 4: val_los

In [12]:
# Step 6: evaluate
loss, accuracy = model_joueur_classique.evaluate(X_test, y_test)

2/2 [==============================] - 0s 3ms/step - loss: 6.0163 - accuracy: 0.3023
Loss:  6.016252517700195
Accuracy:  0.302325576543808


In [13]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
example_input = np.reshape(X_test[0], (1, 50*50*15))
example_input

array([[0., 0., 0., ..., 0., 0., 0.]])

In [15]:
# Step 7: predict
y_pred = model_joueur_classique.predict(example_input)
y_pred

1/1 [==============================] - 0s 56ms/step


array([1], dtype=int64)

In [16]:
# Final step: save the model
model_joueur_classique.save_model('saved_models\classic_model_1_joueur_bas.h5')