In [1]:
from smart.model import NNModelBalle
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

# Read data

In [2]:
df = pd.read_csv("../dataset/new_pos_test.csv")
df.head()

col1_0  col1_1  col2_0  col2_1  col3_0  col3_1  col4_0  col4_1  col5_0  \
0   264.0   269.5   264.0   269.5   264.0   269.5   264.0   269.5   264.0   
1   248.5    78.5   248.5    78.5   248.5    78.5   349.5   187.5   315.5   
2   144.5    84.5   144.0    84.5   144.5    84.5   145.5    83.5   217.5   
3   375.5   203.0   377.5   206.5   379.5   210.0   380.5   214.0   380.0   
4   268.0   175.0   268.0   175.0   268.0   175.0   268.0   175.0   268.0   

   col5_1  ...  col41_1  col42_0  col42_1  col43_0  col43_1  col44_0  col44_1  \
0   269.5  ...    196.5    187.5    202.0    188.0    202.0    184.0    208.0   
1   150.5  ...     82.5    212.0     77.5    212.0     77.5    212.0     77.5   
2    76.5  ...    237.0    293.0    237.0    293.0    237.0    293.0    237.0   
3   214.0  ...    292.5    371.5    291.0    371.5    291.0    371.5    291.0   
4   175.0  ...     79.5    370.0     85.5    365.0     92.5    394.5     52.0   

   col45_0  col45_1  col46  
0    184.0    208.0    2.0  
1    212.0     77.5    2.0  
2    293.0    237.0    2.0  
3    371.5    291.0    2.0  
4    394.5     52.0    2.0  

[5 rows x 91 columns]

In [3]:
# Step 1: Load model
model_balle = NNModelBalle.load_model_from_path("../saved_models/model_balle_2.h5")
model_balle

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_24 (Dense)            (None, 64)                5824      
                                                                 
 dense_25 (Dense)            (None, 96)                6240      
                                                                 
 dense_26 (Dense)            (None, 9)                 873       
                                                                 
Total params: 12,937
Trainable params: 12,937
Non-trainable params: 0
_________________________________________________________________


In [4]:
# Step 2: Read the data
X = df.drop('col46', axis=1)
y = df['col46']

In [5]:
# Step 3: Normalize X and encode y 
possible_outputs = [ 2,  3,  4,  6,  7,  8, 10, 11, 12]

In [6]:
scaler = StandardScaler()
encoder = LabelEncoder()

In [7]:
X = scaler.fit_transform(X)
encoder.fit(possible_outputs)
y = encoder.transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 4, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 8], dtype=int64)

In [8]:
# Step 4: Evaluate the model
loss, accuracy = model_balle.evaluate(X, y)

2/2 [==============================] - 0s 4ms/step - loss: 7.3971 - sparse_categorical_accuracy: 0.3548
Loss:  7.397058486938477
Accuracy:  0.35483869910240173


In [9]:
# Step 5: Predict
y_pred = model_balle.predict(X)
y_pred

2/2 [==============================] - 0s 999us/step


array([1, 0, 2, 7, 0, 6, 0, 0, 0, 2, 0, 7, 0, 0, 7, 1, 0, 7, 3, 7, 1, 0,
       7, 4, 7, 2, 0, 0, 7, 0, 7, 0, 0, 1, 0, 1, 7, 5, 3, 8, 6, 5, 6, 7,
       6, 0, 1, 5, 8, 7, 8, 7, 6, 1, 5, 7, 0, 7, 1, 7, 8, 8], dtype=int64)

In [10]:
# Confusion matrix
confusion_matrix(y, y_pred)

array([[15,  3,  3,  1,  1,  0,  1,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  2,  0,  1,  0,  1,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  3,  0,  0,  0,  3,  4,  6,  2],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2]], dtype=int64)

In [11]:
print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.45      0.59        33
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.50      0.17      0.25         6
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         0
           6       0.80      0.20      0.32        20
           7       0.00      0.00      0.00         0
           8       0.40      1.00      0.57         2

    accuracy                           0.35        62
   macro avg       0.28      0.20      0.19        62
weighted avg       0.76      0.35      0.46        62



c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
