In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from smart.model import RFModelBalle
from sklearn.preprocessing import StandardScaler, LabelEncoder
import joblib
from sklearn.metrics import confusion_matrix, classification_report

In [24]:
df = pd.read_csv('../trajectoire/datasetsimple.csv')
df

0      1      2      3      4      5      6      7      8      9  \
0     231.0  304.0  250.0  287.0  266.0  287.0  252.0  283.0  275.0  284.0   
1     230.0  304.0  239.0  303.0  242.0  297.0  263.0  263.0  281.0  273.0   
2     227.0  306.0  248.0  282.0  247.0  296.0  271.0  278.0  255.0  268.0   
3     236.0  304.0  250.0  280.0  239.0  273.0  251.0  287.0  261.0  261.0   
4     248.0  286.0  251.0  294.0  265.0  296.0  260.0  266.0  269.0  283.0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
4306  544.5  231.0  533.5  216.0  542.0  226.0  542.0  213.0  534.5  213.5   
4307  548.5  223.0  550.5  217.0  539.0  211.0  548.0  222.0  547.5  217.5   
4308  549.5  215.0  537.5  229.0  546.0  207.0  539.0  216.0  539.5  217.5   
4309  550.5  213.0  538.5  221.0  540.0  211.0  551.0  218.0  547.5  226.5   
4310  550.5  221.0  531.5  212.0  544.0  211.0  547.0  213.0  540.5  216.5   

      ...     81     82     83     84     85     86     87     88     89  90  
0     ...   73.0  495.0   56.0  490.0   68.0  516.0   78.0  503.0   62.0   1  
1     ...   74.0  490.0   80.0  502.0   73.0  503.0   64.0  499.0   57.0   1  
2     ...   80.0  502.0   61.0  513.0   66.0  493.0   57.0  522.0   51.0   1  
3     ...   78.0  483.0   78.0  501.0   76.0  509.0   63.0  500.0   63.0   1  
4     ...   82.0  484.0   77.0  496.0   73.0  491.0   65.0  512.0   56.0   1  
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  ..  
4306  ...  250.0  584.0  259.0  567.5  284.0  573.0  279.0  577.0  288.0  13  
4307  ...  258.0  581.0  259.0  569.5  285.0  582.0  272.0  589.0  283.0  13  
4308  ...  245.0  573.0  260.0  574.5  292.0  582.0  284.0  589.0  282.0  13  
4309  ...  251.0  580.0  259.0  579.5  283.0  592.0  289.0  591.0  287.0  13  
4310  ...  261.0  566.0  274.0  579.5  296.0  588.0  273.0  576.0  273.0  13  

[4311 rows x 91 columns]

In [38]:
# Step 1: load the model
model_balle = RFModelBalle.construct_model(max_depth = 8, n_estimators = 20)
model_balle

In [39]:
# Step 2: Read the data
X = df.drop(['90'], axis=1)
y = df['90']
y

0        1
1        1
2        1
3        1
4        1
        ..
4306    13
4307    13
4308    13
4309    13
4310    13
Name: 90, Length: 4311, dtype: int64

In [40]:
# Step 3: Normalize X and encode y 
possible_outputs = [ 1,  3,  4,  6,  7,  8, 10, 11, 12,13]

In [41]:
scaler = StandardScaler()
encoder = LabelEncoder()

In [42]:
X = scaler.fit_transform(X)
encoder.fit(possible_outputs)
y = encoder.transform(y)
y

array([0, 0, 0, ..., 9, 9, 9], dtype=int64)

In [43]:
X_train, X_test, y_train, y_test = model_balle.train_test_split(X, y)

In [44]:

model_balle.fit(X_train, y_train)

In [45]:
# Step 4: Evaluate the model
score = model_balle.evaluate(X, y)
score

0.9990721410345628

In [50]:
model_balle.save_model('../saved_models/model_balle_1.joblib')

In [ ]:
df_test = pd.read_csv('../trajectoire/dataset.csv')

In [46]:
# Step 5: Predict
y_pred = model_balle.predict(X)
y_pred, y

(array([0, 0, 0, ..., 9, 9, 9], dtype=int64),
 array([0, 0, 0, ..., 9, 9, 9], dtype=int64))

In [47]:
# Confusion matrix
confusion_matrix(y, y_pred)

array([[1273,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,  408,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,  408,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,  408,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,  204,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,  153,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,  510,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,  306,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,  306,    0],
       [   3,    0,    1,    0,    0,    0,    0,    0,    0,  331]],
      dtype=int64)

In [34]:
print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       0.74      0.42      0.54        33
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         6
           4       0.33      1.00      0.50         1
           5       0.00      0.00      0.00         0
           6       0.46      0.30      0.36        20
           7       0.00      0.00      0.00         0
           8       0.67      1.00      0.80         2

    accuracy                           0.37        62
   macro avg       0.24      0.30      0.24        62
weighted avg       0.57      0.37      0.44        62



c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
