In [22]:
from smart.model import ModelBalle
import pandas as pd
import math
import numpy as np

# Read data

In [3]:
df = pd.read_csv("dataset/pos.csv")
df.head()

col1        col2        col3        col4        col5        col6  \
0  (175, 232)  (184, 227)  (195, 229)  (200, 215)  (196, 213)  (206, 214)   
1  (176, 232)  (191, 229)  (188, 233)  (200, 216)  (205, 217)  (208, 210)   
2  (176, 236)  (191, 226)  (196, 227)  (200, 221)  (199, 221)  (198, 214)   
3  (176, 238)  (184, 236)  (191, 224)  (189, 214)  (194, 215)  (198, 210)   
4  (176, 242)  (185, 231)  (191, 228)  (187, 224)  (195, 219)  (205, 215)   

         col7        col8        col9       col10  ...       col37  \
0  (215, 214)  (207, 208)  (217, 194)  (217, 195)  ...  (350, 126)   
1  (211, 213)  (215, 209)  (221, 196)  (218, 191)  ...  (346, 128)   
2  (214, 204)  (212, 206)  (224, 192)  (219, 194)  ...  (350, 129)   
3  (206, 204)  (216, 211)  (216, 195)  (218, 188)  ...  (346, 128)   
4  (202, 207)  (218, 208)  (220, 199)  (219, 198)  ...  (347, 127)   

        col38       col39       col40       col41       col42       col43  \
0  (358, 136)  (356, 121)  (360, 125)  (370, 119)  (374, 114)  (371, 110)   
1  (354, 124)  (357, 117)  (361, 122)  (364, 121)  (377, 110)  (374, 107)   
2  (352, 131)  (362, 120)  (357, 119)  (361, 113)  (375, 106)  (377, 110)   
3  (359, 124)  (360, 122)  (357, 119)  (365, 120)  (368, 105)  (380, 108)   
4  (353, 127)  (358, 120)  (362, 114)  (369, 113)  (374, 105)  (373, 109)   

        col44       col45 col46  
0  (380, 108)   (391, 93)     2  
1   (383, 97)  (382, 101)     2  
2   (378, 97)   (383, 95)     2  
3   (384, 96)   (386, 94)     2  
4   (380, 98)  (392, 102)     2  

[5 rows x 46 columns]

In [4]:
model_balle = ModelBalle.construct_model(n_estimators = 100)
model_balle

In [5]:
X = df.drop('col46', axis=1)
y = df['col46']

In [6]:
def conv(a):  
    a = a[1:len(a) - 1]
    l = a.split(',')
    return math.sqrt(math.pow(float(l[0]), 2) + math.pow(float(l[1]), 2))

In [7]:
data_size = 6463
for col in X:
    for lig in range(data_size):
        X[col][lig] = conv(X[col][lig])

In [8]:
# Step 1: Split the data
X_train, X_test, y_train, y_test = model_balle.train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((5170, 45), (1293, 45), (5170,), (1293,))

In [9]:
# Step 2: Fit the model
model_balle.fit(X_train, y_train)

In [10]:
# Step 3: Evaluate the model
model_balle.evaluate(X_test, y_test)

0.9984532095901005

In [12]:
# Step 4: Predict
y_pred = model_balle.predict(X_test)
y_pred

array([ 3,  6, 10, ..., 12,  2, 10], dtype=int64)

In [13]:
# Final Step: Save the model
model_balle.save_model("saved_models/model_balle_1.joblib")

--------------------------------------------------------------------------------------------------------------------------------------

# Test loading the model from disk (do not need to train)

In [14]:
# Test loading the model from disk
model_balle = ModelBalle.load_model_from_path('saved_models/model_balle_1.joblib')
model_balle

- Convertir les données en 2-dim avant de prédire

In [23]:
X_to_test = np.array(X_test.iloc[0]).reshape(1, -1)
X_to_test

array([[293.218348675522, 295.67718883945037, 306.2025473440742,
        307.9366818032564, 311.52046481732145, 309.9193443462347,
        315.54555930958685, 310.39490975207696, 315.29827148273426,
        322.44844549167857, 319.2882710028666, 314.14805426741066,
        312.385979198811, 319.7811751807789, 324.7845439672276,
        321.6286678764814, 324.0385779502188, 332.0557182160849,
        337.7217789838257, 346.0014450836875, 333.7019628351023,
        339.69545183884935, 339.3287491504367, 340.75357665034124,
        347.7010209936117, 351.38582783032103, 354.268259938708,
        350.65652710308984, 360.25685281476603, 359.1670920337775,
        357.8337602854152, 358.2206024225854, 362.70787143374764,
        361.7982863419892, 360.9348971767623, 361.809342057388,
        368.63532115086315, 370.3147310059377, 367.25059564281173,
        367.87090126836614, 375.7658845611187, 378.00132274900835,
        371.7216700704978, 379.2888081660201, 387.7434718986253]],
      dtyp

In [31]:
model_balle.predict(X_to_test)

c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([3], dtype=int64)