In [21]:
from smart.model import ModelJoueurClassique
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, BatchNormalization, Dropout
import numpy as np

In [22]:
path_dataset = 'img/JHaut'

In [23]:
model_joueur_classique = ModelJoueurClassique.load_model_from_path("saved_models/classic_model_1_joueur_haut.h5")
model_joueur_classique.summary_model

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                600016    
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 64)                2112      
                                                                 
 dense_3 (Dense)             (None, 128)               8320      
                                                                 
 dense_4 (Dense)             (None, 4)                 516       
                                                                 
Total params: 611,508
Trainable params: 611,508
Non-trainable params: 0
_________________________________________________________________


In [24]:
# Step 1: Load the data
list_videos, y = model_joueur_classique.analyse_sequence_frame(path_data_frame=path_dataset)
len(list_videos), len(y)

(144, 144)

In [25]:
# Step 2: Label encoder
y = model_joueur_classique.label_encoder(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

In [26]:
# Step 3: Split the data
X_train, y_train, X_test, y_test = model_joueur_classique.split_train_test(list_videos, y)
X_train.shape

(115, 37500)

In [27]:
# Step 4: Normalize the data
X_train, X_test = model_joueur_classique.normalize_input(X_train, X_test)

In [30]:
# Step 5: Train the model
history = model_joueur_classique.train(X_train, y_train, epochs=70)

Epoch 1/70
1/3 [=========>....................] - ETA: 0s - loss: 1.6197e-05 - accuracy: 1.0000
Epoch 1: val_loss improved from inf to 3.88633, saving model to checkpoints\Weights-001--3.88633.hdf5
3/3 [==============================] - 1s 76ms/step - loss: 1.3710e-05 - accuracy: 1.0000 - val_loss: 3.8863 - val_accuracy: 0.3913
Epoch 2/70
1/3 [=========>....................] - ETA: 0s - loss: 8.6797e-06 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 3.88633
3/3 [==============================] - 0s 24ms/step - loss: 8.5350e-06 - accuracy: 1.0000 - val_loss: 4.0833 - val_accuracy: 0.3913
Epoch 3/70
1/3 [=========>....................] - ETA: 0s - loss: 7.6293e-06 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 3.88633
3/3 [==============================] - 0s 28ms/step - loss: 6.1573e-06 - accuracy: 1.0000 - val_loss: 4.3434 - val_accuracy: 0.3478
Epoch 4/70
1/3 [=========>....................] - ETA: 0s - loss: 8.2440e-06 - accuracy: 1.0000
Epoch 4: val_loss did no

In [31]:
# Step 6: evaluate
loss, accuracy = model_joueur_classique.evaluate(X_test, y_test)

1/1 [==============================] - 0s 18ms/step - loss: 10.6794 - accuracy: 0.0690
Loss:  10.679405212402344
Accuracy:  0.06896551698446274


In [24]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
example_input = np.reshape(X_test[0], (1, 50*50*15))
example_input

array([[0., 0., 0., ..., 0., 0., 0.]])

In [26]:
# Step 7: predict
y_pred = model_joueur_classique.predict(example_input)
y_pred

1/1 [==============================] - 0s 65ms/step


array([0], dtype=int64)

In [29]:
possible_outputs = ['coup droit', 'revers', 'service', 'deplacement']

In [30]:
pred_label = model_joueur_classique.predict_label(example_input, possible_outputs)
pred_label

1/1 [==============================] - 0s 21ms/step


array(['coup droit'], dtype='<U11')

In [28]:
# Final step: save the model
model_joueur_classique.save_model('saved_models/classic_model_1_joueur_haut.h5')