In [120]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import xgboost as xgb

In [121]:
df = pd.read_csv('dataset/new_pos.csv')
df.head()

col1_0  col1_1  col2_0  col2_1  col3_0  col3_1  col4_0  col4_1  col5_0  \
0   175.0   232.0   184.0   227.0   195.0   229.0   200.0   215.0   196.0   
1   176.0   232.0   191.0   229.0   188.0   233.0   200.0   216.0   205.0   
2   176.0   236.0   191.0   226.0   196.0   227.0   200.0   221.0   199.0   
3   176.0   238.0   184.0   236.0   191.0   224.0   189.0   214.0   194.0   
4   176.0   242.0   185.0   231.0   191.0   228.0   187.0   224.0   195.0   

   col5_1  ...  col41_1  col42_0  col42_1  col43_0  col43_1  col44_0  col44_1  \
0   213.0  ...    119.0    374.0    114.0    371.0    110.0    380.0    108.0   
1   217.0  ...    121.0    377.0    110.0    374.0    107.0    383.0     97.0   
2   221.0  ...    113.0    375.0    106.0    377.0    110.0    378.0     97.0   
3   215.0  ...    120.0    368.0    105.0    380.0    108.0    384.0     96.0   
4   219.0  ...    113.0    374.0    105.0    373.0    109.0    380.0     98.0   

   col45_0  col45_1  col46  
0    391.0     93.0    2.0  
1    382.0    101.0    2.0  
2    383.0     95.0    2.0  
3    386.0     94.0    2.0  
4    392.0    102.0    2.0  

[5 rows x 91 columns]

In [122]:
df.describe()

col1_0       col1_1       col2_0       col2_1       col3_0  \
count  6463.000000  6463.000000  6463.000000  6463.000000  6463.000000   
mean    301.635928   172.079375   301.376141   169.084326   301.932230   
std      75.307941    70.621681    74.091861    67.475299    72.442872   
min     164.000000    88.000000   170.000000    87.000000   176.000000   
25%     246.000000   102.000000   245.000000   102.000000   247.000000   
50%     305.000000   222.000000   305.000000   215.000000   305.000000   
75%     361.000000   243.000000   360.000000   237.000000   358.000000   
max     435.000000   257.000000   432.000000   251.000000   428.000000   

            col3_1       col4_0       col4_1       col5_0       col5_1  ...  \
count  6463.000000  6463.000000  6463.000000  6463.000000  6463.000000  ...   
mean    166.213523   301.843571   163.366084   301.711898   160.375058  ...   
std      64.807385    71.027193    62.238422    69.215780    59.296313  ...   
min      79.000000   177.000000    79.000000   177.000000    72.000000  ...   
25%     102.000000   248.000000   104.000000   249.000000   106.000000  ...   
50%     211.000000   304.000000   205.000000   305.000000   195.000000  ...   
75%     231.000000   357.000000   225.000000   355.000000   220.000000  ...   
max     245.000000   425.000000   242.000000   425.000000   236.000000  ...   

           col41_1      col42_0      col42_1      col43_0      col43_1  \
count  6463.000000  6463.000000  6463.000000  6463.000000  6463.000000   
mean    155.641343   299.240755   155.738357   299.663160   156.079684   
std      54.250629    67.574223    57.554642    69.739207    60.446863   
min      76.000000   155.000000    73.000000   152.000000    70.000000   
25%     102.000000   249.000000    99.000000   247.000000    95.000000   
50%     143.000000   301.000000   140.000000   302.000000   138.000000   
75%     209.000000   351.000000   213.000000   353.000000   217.000000   
max     251.000000   452.000000   254.000000   455.000000   258.000000   

           col44_0      col44_1      col45_0      col45_1        col46  
count  6463.000000  6463.000000  6463.000000  6463.000000  6463.000000  
mean    299.417763   156.613337   299.710351   157.583475     6.844499  
std      71.757387    63.541532    73.292565    66.932465     3.456067  
min     146.000000    67.000000   143.000000    64.000000     2.000000  
25%     246.000000    92.000000   244.000000    89.000000     4.000000  
50%     303.000000   137.000000   303.000000   135.000000     7.000000  
75%     355.000000   222.000000   356.500000   228.000000    10.000000  
max     458.000000   261.000000   462.000000   265.000000    12.000000  

[8 rows x 91 columns]

In [123]:
X = df.drop('col46', axis=1).values
y = df['col46'].values

In [124]:
X.shape

(6463, 90)

In [125]:
scaler = StandardScaler()

In [126]:
# Normalize the data
X = scaler.fit_transform(X)
X

array([[-1.68170479,  0.84853915, -1.58432007, ..., -0.76512318,
         1.24564767, -0.96497973],
       [-1.66842495,  0.84853915, -1.48983544, ..., -0.93825169,
         1.12284263, -0.84544702],
       [-1.66842495,  0.90518336, -1.48983544, ..., -0.93825169,
         1.13648763, -0.93509655],
       ...,
       [ 1.62497524,  1.01847178,  1.58766371, ..., -1.19007499,
         0.03124227, -1.27875309],
       [ 1.62497524,  1.07511599,  1.5471703 , ..., -1.26876977,
        -0.02333775, -1.29369468],
       [ 1.62497524,  1.07511599,  1.5336725 , ..., -1.19007499,
         0.00395226, -1.23392832]])

In [127]:
encoder = LabelEncoder()

In [128]:
y = encoder.fit_transform(y)
y

array([0, 0, 0, ..., 8, 8, 8], dtype=int64)

In [129]:
X_train, X_validation, y_train, y_validation = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape

(5170, 90)

# XGBoost

In [130]:
# Create classification matrices
dtrain_clf = xgb.DMatrix(X_train, y_train)
dvalid_clf = xgb.DMatrix(X_validation, y_validation)

In [105]:
params = {"objective": "multi:softprob", "num_class": 9}
n = 80

results = xgb.cv(
   params, dtrain_clf,
   num_boost_round=n,
   nfold=5,
   metrics=["mlogloss", "auc", "merror"],
)

In [106]:
results.keys()

Index(['train-mlogloss-mean', 'train-mlogloss-std', 'train-auc-mean',
       'train-auc-std', 'train-merror-mean', 'train-merror-std',
       'test-mlogloss-mean', 'test-mlogloss-std', 'test-auc-mean',
       'test-auc-std', 'test-merror-mean', 'test-merror-std'],
      dtype='object')

In [107]:
results['train-merror-mean'].max()

0.001885880077369436

In [108]:
clf = xgb.train(params, dtrain_clf, n, evals=[(dvalid_clf, "Validation")], verbose_eval=10)

[0]	Validation-mlogloss:1.08063
[10]	Validation-mlogloss:0.05544
[20]	Validation-mlogloss:0.00759
[29]	Validation-mlogloss:0.00389


# Test DataFrame

In [109]:
df_test = pd.read_csv('dataset/new_pos_test.csv')

In [110]:
X_test = df_test.drop('col46', axis=1).values
y_test = df_test['col46'].values
y_test

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  6.,  6.,  6.,  6.,  6.,  6.,
        7., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 12., 12.])

In [111]:
new_scaler = StandardScaler()

In [112]:
# Normalize the data
X_test = new_scaler.fit_transform(X_test)
X_test

array([[-0.44126302,  1.73114769, -0.62021034, ...,  0.53877629,
        -1.07149312,  0.51503057],
       [-0.69122102, -0.82738597, -0.89924692, ..., -1.19970385,
        -0.73968576, -1.1868736 ],
       [-2.36835862, -0.74701318, -2.78049355, ...,  0.92510521,
         0.22018553,  0.8932315 ],
       ...,
       [-0.58639992, -1.32971587,  0.5319407 , ...,  0.05253472,
         0.196485  , -0.11747787],
       [ 0.71176908, -1.45697278,  0.6669584 , ..., -0.83335746,
         0.15500908, -0.82171409],
       [-0.79604212, -1.63781155, -1.02526344, ...,  0.85183593,
         0.01280593,  0.82150374]])

In [113]:
y_test = encoder.transform(y_test)
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 4, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 8], dtype=int64)

In [114]:
dtest_clf = xgb.DMatrix(X_test, y_test)

In [115]:
prediction = clf.predict(dtest_clf)
prediction

array([[2.53782631e-03, 9.79276776e-01, 7.60651939e-03, 1.72407273e-03,
        1.62721192e-03, 1.45894126e-03, 1.82342529e-03, 2.49106740e-03,
        1.45423634e-03],
       [1.48749109e-02, 6.63408311e-03, 5.63994376e-03, 9.39884484e-01,
        6.32877415e-03, 5.05691487e-03, 1.03073632e-02, 6.23288751e-03,
        5.04060695e-03],
       [2.91344404e-01, 9.86378193e-02, 1.28371790e-01, 7.27517456e-02,
        6.84244335e-02, 6.13486208e-02, 1.24767266e-01, 8.00638646e-02,
        7.42900595e-02],
       [5.50569445e-02, 1.22837583e-03, 6.35030679e-04, 1.15287316e-03,
        7.74111308e-04, 6.13891287e-04, 9.38592851e-01, 1.33396673e-03,
        6.11911528e-04],
       [9.98898864e-01, 1.47837171e-04, 1.20958197e-04, 1.83673052e-04,
        1.07135951e-04, 9.78037133e-05, 2.27038996e-04, 1.19198128e-04,
        9.74883078e-05],
       [8.00871931e-04, 6.31331641e-04, 6.46305678e-04, 1.23323500e-03,
        4.93991654e-04, 4.50962019e-04, 9.94411290e-01, 8.82532040e-04,
        4.4

In [116]:
y_pred = np.asarray([np.argmax(line) for line in prediction])
y_pred

array([1, 3, 0, 6, 0, 6, 0, 0, 0, 1, 6, 7, 1, 0, 5, 1, 6, 7, 3, 7, 2, 1,
       7, 4, 5, 2, 6, 0, 5, 0, 2, 0, 6, 0, 0, 4, 3, 2, 0, 6, 6, 2, 6, 7,
       6, 6, 1, 5, 2, 6, 2, 7, 6, 1, 5, 2, 6, 1, 1, 8, 8, 8], dtype=int64)

In [117]:
confusion_matrix(y_test, y_pred)

array([[9, 5, 3, 2, 1, 3, 6, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 0, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 4, 4, 0, 0, 2, 7, 2, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 2]], dtype=int64)

In [118]:
cpt = 0
for i in range(len(y_pred)):
    if y_pred[i] == y_test[i]:
        cpt += 1
cpt/len(y_pred)

0.3064516129032258

In [119]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.27      0.40        33
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.33      0.17      0.22         6
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         0
           6       0.50      0.35      0.41        20
           7       0.00      0.00      0.00         0
           8       0.67      1.00      0.80         2

    accuracy                           0.31        62
   macro avg       0.25      0.20      0.20        62
weighted avg       0.61      0.31      0.39        62



c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
